"""delete title add anime_id

Revision ID: 215a01eb0922
Revises: 98db99834a03
Create Date: 2025-04-13 09:13:25.749710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215a01eb0922'
down_revision: Union[str, None] = '98db99834a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('anime_id', sa.Integer(), nullable=True))
    op.drop_column('anime', 'title')
    op.add_column('anime_mistral', sa.Column('anime_id', sa.Integer(), nullable=True))
    op.drop_column('anime_mistral', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime_mistral', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('anime_mistral', 'anime_id')
    op.add_column('anime', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('anime', 'anime_id')
    # ### end Alembic commands ###
