"""add cover column

Revision ID: 36980a959640
Revises: 7b08fb588aa1
Create Date: 2025-04-14 21:01:19.710542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36980a959640'
down_revision: Union[str, None] = '7b08fb588aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime_mistral', sa.Column('cover', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime_mistral', 'cover')
    # ### end Alembic commands ###
