"""add title columns

Revision ID: 7b08fb588aa1
Revises: def88828c81c
Create Date: 2025-04-14 13:08:45.451792

"""

import pickle
from pathlib import Path
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b08fb588aa1"
down_revision: Union[str, None] = "def88828c81c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # """Upgrade schema."""
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("anime", sa.Column("title_english", sa.String(), nullable=True))
    op.add_column("anime", sa.Column("title_native", sa.String(), nullable=True))
    op.add_column("anime", sa.Column("title_romaji", sa.String(), nullable=True))
    op.add_column(
        "anime_mistral", sa.Column("title_english", sa.String(), nullable=True)
    )
    op.add_column(
        "anime_mistral", sa.Column("title_native", sa.String(), nullable=True)
    )
    op.add_column(
        "anime_mistral", sa.Column("title_romaji", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###

    op.execute("""
        UPDATE anime_mistral
        SET
            title_english = doc->>'title_english',
            title_native = doc->>'title_native';
    """)

    connection = op.get_bind()

    data = pickle.load(
        open(Path(__file__).parent.parent.parent / "data" / "anime.pkl", "rb")
    )

    for _, anime in data.iterrows():
        id = anime["id"]
        title_romaji = anime["title_romaji"]

        title_romaji = title_romaji.replace("'", "''")

        query = f"""
            UPDATE anime_mistral
            SET
                title_romaji = '{title_romaji}'
            WHERE
                anime_id = {id};
        """
        connection.execute(sa.text(query))


def downgrade():
    op.execute("""
        UPDATE anime_mistral
        SET
            title_english = NULL,
            title_native = NULL;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("anime_mistral", "title_romaji")
    op.drop_column("anime_mistral", "title_native")
    op.drop_column("anime_mistral", "title_english")
    op.drop_column("anime", "title_romaji")
    op.drop_column("anime", "title_native")
    op.drop_column("anime", "title_english")
    # ### end Alembic commands ###
