"""mistral entries

Revision ID: 98db99834a03
Revises: 3406434b6ded
Create Date: 2025-04-11 18:35:29.334594

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98db99834a03"
down_revision: Union[str, None] = "3406434b6ded"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anime_mistral",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("doc", sa.JSON(), nullable=True),
        sa.Column(
            "vectors", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("anime_mistral")
    # ### end Alembic commands ###
